---
dist: bionic
language: python
python:
  - "3.5"
  - "3.8"

install:
  - pip install numpy scipy matplotlib gsw munch pdoc
  - pip install .

script:
  - mkdir docs
  - pdoc --html -o ./docs --force gvpy
  - mv ./docs/gvpy/*.html ./docs/
  - rm -rf ./docs/gvpy

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    target_branch: gh-pages
    on:
      branch: master